# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a09f707cafcf92920ffe0d237e1202b11ae6a5fc7cfc9f35234d583e47733f32bef88ba6b5b2dfb8390b955e920e1df8f02a413133557d3ba7797c1643ea8ffe

test:
  secret_key_base: 755d14998df4ab5f391e7ce6ac22e4f2b43bb3ad505627735c788af99948ba4459cd9bdf3190beaebcbbde2d9251b79ec91adc78da17bc272ae953dab3f1a549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
